### ISSUE TITLE
ML model

### ISSUE THREAD

**Issue by zneha** [AutoViML/Auto_TS#1]
Nice work! Just wondering, if in future, there will be additional ML models added like LSTM or CNN etc., other than what is currently present, which is Random Forest?

I actually encountered this error while "pip installing"

ERROR: Command errored out with exit status 1:

**Comment by AutoViML** [comment]
Yes that’s the plan.
Ram

**Comment by AutoViML** [comment]
Neha:
Can you please show us a screenshot or where you encountered this error (is it in a Colab or in your desktop?) etc.
That will help us troubleshoot the problem.
Ram

**Comment by zneha** [comment]
This is on the mac desktop that I encountered the error.

"ERROR: Failed building wheel for pyflux"

**Comment by AutoViML** [comment]
You should look at installing pyflux separately on your Mac using the
instructions on pyflux website (google it). That’s because PyFlux is a
finicky tool. It doesn’t install easily. So better to install it separately
at first and then try installing auto-TS. Hope this resolves the issue. Let
me know.
Thanks.

**Comment by zneha** [comment]
Perfect, got through it! Thanks! Ans also, great work again :)
