### ISSUE TITLE
__init__() got an unexpected keyword argument 'test_size'

### ISSUE THREAD

**Issue by Priyabrata409** [AutoViML/Auto_TS#38]
TimeSeriesSplit has no argument  called " test_size"

**Comment by Priyabrata409** [comment]
While creating Prophet crossvalidation this error is showing.

**Comment by AutoViML** [comment]
I have fixed the bug - I used a sklearn feature which is not out until
0.0.24 version which was just released a few days ago. Not everyone has
this upgraded version. I reverted back to an older version which works.
Please do the following:
" pip install auto_ts --upgrade" and see if you have the latest version as
0.0.33

If you see that version in your notebook when you "import auto_ts" then
this bug is fixed.
Ram

**Comment by Priyabrata409** [comment]
Yes, I updated my Scikit learn to 0.24.0 and the issue is solved now.
