### ISSUE TITLE
Installation issues on Windows

### ISSUE THREAD

**Issue by JimmyBroomfield** [AutoViML/Auto_TS#44]
**Description of issue:**  Installation seems to fail on Windows machines.

**Suspected reasons:**

1. The pip installer has difficulty building the fbprophet wheel because the dependencies aren't installed before the wheel is built (see [related issue](https://github.com/facebook/prophet/issues/1760))

2. Installation of fbprophet requires pystan.  On Windows, Pystan requires a compiler.  A pip install pystan command won't result in a proper installation on Windows.  Instead, fbprophet recommends using Anaconda for installation (see [fbprophet install docs](https://facebook.github.io/prophet/docs/installation.html))

I've attached some screenshots to show the errors during installation:

(initial try)
![image](https://user-images.githubusercontent.com/33099097/109544255-f3d89680-7a8c-11eb-8a14-d06b9e20faff.png)

(after installing dependencies manually)
![image](https://user-images.githubusercontent.com/33099097/109544454-339f7e00-7a8d-11eb-9cc0-362dad7ed540.png)
![image](https://user-images.githubusercontent.com/33099097/109545066-f8517f00-7a8d-11eb-84ad-b1f2e2cac263.png)

**Additional Note:** The issue shown in the second and third screen shot is probably tied to the C++ complier being referenced on my machine.  This might work fine on other Windows machines (depending on local settings) however this isn't the point.  The main point is that a note should be made in the installation directions to help those running windows.

**Comment by AutoViML** [comment]
Hi Jimmy:
the good news for installing FB prophet on Windows is to use Anaconda! It works like charm.

Just try:
$ conda install -c conda-forge fbprophet.

You will find that you don't need anything else. Trust me, I run FB Prophet on Windows too,. Here is the link:
https://facebook.github.io/prophet/docs/installation.html

Ram

**Comment by AutoViML** [comment]
HiI run Auto_TS and FB Prophet on Windows 10 on my laptop. So you should be able to.
Here's how I do it:
Install FB prophet easily through conda-forge = it worked like a charm for me on Windows.
Just type on your Command prompt:

$ conda install -c conda-forge fbprophet.
If you still have problems, try:$ conda install gcc 
Then try the command again above.Hope this helps,Ram
    On Monday, March 1, 2021, 2:05:54 PM EST, JimmyBroomfield ***@***.***> wrote:  
 
 


Description of issue: Installation seems to fail on Windows machines.

Suspected reasons:
   
   -    
The pip installer has difficulty building the fbprophet wheel because the dependencies aren't installed before the wheel is built (see related issue)

   -    
Installation of fbprophet requires pystan. On Windows, Pystan requires a compiler. A pip install pystan command won't result in a proper installation on Windows. Instead, fbprophet recommends using Anaconda for installation (see fbprophet install docs)


I've attached some screenshots to show the errors during installation:

(initial try)


(after installing dependencies manually)



Additional Note: The issue shown in the second and third screen shot is probably tied to the C++ complier being referenced on my machine. This might work fine on other Windows machines (depending on local settings) however this isn't the point. The main point is that a note should be made in the installation directions to help those running windows.
