### ISSUE TITLE
"['ds'] not in index"

### ISSUE THREAD

**Issue by rnjv** [AutoViML/Auto_TS#67]
I get, not sure why:

Running Facebook Prophet Model...
(Error): You have not provided the time_column values. This will result in an error
Exception occurred while building Prophet model...
"['ds'] not in index"
    FB Prophet may not be installed or Model is not running...

**Comment by AutoViML** [comment]
Hi @rnjv :
Unless you can provide your sample data by cut paste here (even 10 rows will do), I cannot trouble this. Please understand there may be many reasons for this since I don't know your machine or environment. Unless you give me some data to 
work (or even a link to Github notebook or a colab notebook), I can't troubleshoot these kind of issues.
