### ISSUE TITLE
Is Multiple Time Series with multiple regressors supported?

### ISSUE THREAD

**Issue by ghost** [AutoViML/Auto_TS#74]
Hi, 

I'm exploring the package and so far it works just fine. I'm thinking about a situation where we have hundreds of thousands of different time series with time varying features. That is, at forecast (or prediction) time, the values of the future time regressors to be forecast are known. Whilst it's possible to build single forecast for each series, however one combined model is preferred because it allows for information sharing or some sort of global information.

Is this type of forecast setup supported in this current implementation?

**Comment by AutoViML** [comment]
Hi @goleng 👍 

I am currently testing a version that can handle hundreds of time series with time varying features. But it uses a Supervised ML approach and hence you will need to provide regressors at least for the forecast period that you are looking ahead. For example if you have 2 predictors (Store and SKU), for each target ('Sales') then you need to provide at least the Store number and SKU value for each of the future forecast period. Otherwise, what exactly is it predicting? Nothing. Hence if you are interested in testing out this version, I can provide a test pypi link where you can pip install that version for your data alone and test it. Let me know.
Thanks,
Auto-TS team

**Comment by ghost** [comment]
@AutoViML Thanks for your response. Yes, that's exactly what I'm looking for. It's more of an ML approach then classical time series forecast. I'll appreciate it if you could share the pypi link or the git branch

**Comment by AutoViML** [comment]
@goleng 👍 

I have uploaded a new version 0.0.62 to address the multi-store multi-item problem. Just do this:
``` pip install --auto_ts --upgrade```

You can try the same way as before and see if this works.
thanks
Auto_ViML
