### ISSUE TITLE
Google Colab import error

### ISSUE THREAD

**Issue by nicolasseverino** [AutoViML/Auto_TS#79]
Hi ! I wanted to try out your framework but although I manage to install it on Google Colab, I can't import it :

If I write in a cell :
> from auto_ts import auto_timeseries

I get :
> "load() missing 1 required positional argument: 'Loader'"

Obviously, it seems coming from "yaml.load(f)". How can I import and use it on Google Colab then please ?

Thanks for your help !

**Comment by AutoViML** [comment]
Hi @nicolasseverino 👍 
Please double check if you are using the right "auto_ts" library. There are 2 libraries with similar name: "autots" and "auto_ts".

Second, please paste a screenshot of the error. I could have seen where the error was coming from. Otherwise, it is hard.

Thanks
AutoViML

**Comment by AutoViML** [comment]
Hi @nicolasseverino :

The following three steps worked for me in Colab - do this one after another in each cell.
```
!pip install auto-ts --no-deps --ignore-installed
!pip install 'fsspec>=0.3.3'
!pip install statsmodels
```
But please restart the runtime (look up in the Colab Runtime menu) after installing statsmodels and then do this:
```
from auto_ts import auto_timeseries
```
Voila! that worked for me.
Autovimal

**Comment by RenaissanceEngineering** [comment]
Still isn't working at all for me. Same error, tried all the installations also with Conda on Colab execution fails. Is there any alternative for cloud services?

**Comment by RenaissanceEngineering** [comment]
> `from auto_ts import auto_timeseries`

Error following exact steps:

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-1-53a15f3ccdf8>](https://localhost:8080/#) in <module>
----> 1 from auto_ts import auto_timeseries

3 frames

[/usr/local/lib/python3.7/dist-packages/auto_ts/models/ar_based/build_autoarimax.py](https://localhost:8080/#) in <module>
      6 # TODO: Resolve which one we want to use
      7 #from pmdarima.arima.auto import auto_arima # type: ignore
----> 8 from pmdarima.arima import auto_arima # type: ignore
      9 
     10 

ModuleNotFoundError: No module named 'pmdarima'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by mohsinrazadev** [comment]
`from auto_ts import auto_timeseries`

Error :
OSError: dlopen(/Users/name/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/name/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

**Comment by AutoViML** [comment]
Hi:
Anyone with this link can open this Colab and see auto_ts is imported. Google Colaboratory


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Google Colaboratory


 |

 |

 |



Let me reproduce the steps here!pip3 install auto-ts --no-deps --ignore-installed
!pip install 'fsspec>=0.3.3'
!pip install pmdarima
Restart the Colab run-time and do the imports. It should work fine.AutoVimal 
    On Tuesday, March 28, 2023 at 06:43:04 AM EDT, Mohsin Raza ***@***.***> wrote:  
 
 


from auto_ts import auto_timeseries

Error :
OSError: dlopen(/Users/name/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
Referenced from: /Users/name/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
Reason: image not found
