### ISSUE TITLE
Issues with `prophet` cause variables to be left undefined

### ISSUE THREAD

**Issue by cgobat** [AutoViML/Auto_TS#97]
Issue was originally noted in facebook/prophet#2392.

In [this module's `__init__.py`](https://github.com/AutoViML/Auto_TS/blob/master/auto_ts/__init__.py#L549-L577), there is a `try` block wherein a `BuildProphet` instance is created and `BuildProphet.fit()` is called. If an exception is raised within this block, the `except Exception as e` statement will catch it and print the error, but variables such as `forecast_df_folds` will not be defined, which raises an error when `forecast_df_folds` is referenced a few lines later.

**Comment by cgobat** [comment]
For posterity, it is worth noting that this issue seems to be either related to or the same as #39.

**Comment by AutoViML** [comment]
Yes I have added this             forecast_df_folds = Nonein the except part of the code.
Please upgrade to the latest version 0.71 and try again.
ThanksAuto Vimal    On Monday, March 27, 2023 at 06:30:23 PM EDT, Caden Gobat ***@***.***> wrote:  
 
 


For posterity, it is worth noting that this issue seems to be either related to or the same as #39.
